"""The generated half of the command table: `rpc/schema.py`.

`docs/REMOTE-CONTROL.md` §6 rejected generating the wire from decorated
`AgentSession` methods, for six reasons. Three of them (A1 layer inversion, A3
Python-signature coupling, A6 import-order) do not reach a table the core declares
for its own use, so the STRUCTURE of a capability-backed verb's params schema is
now derived from `CAPABILITIES` and only its prose is hand-written. The two
objections that still hold are pinned here too: a verb with no capability keeps its
literal (A2), and a declined verb has no capability at all (A4).

The strongest evidence that the derivation preserved the wire is not in this file:
`docs/RPC-PROTOCOL.md` regenerated byte-identical, and
`test_rpc_protocol_doc.py::test_checked_in_doc_matches_the_generator` is what keeps
it so.
"""

from __future__ import annotations

import pytest

from tau_agent_core.capabilities import CAPABILITIES, DOMAINS
from tau_agent_core.rpc.commands import COMMAND_TABLE
from tau_agent_core.rpc.schema import _DOMAIN_TYPES, params_schema_for


def _structure(schema: dict) -> dict:
    """The schema minus its prose — what the registry is authoritative for."""
    return {
        "type": schema["type"],
        "required": sorted(schema.get("required", [])),
        "additionalProperties": schema.get("additionalProperties"),
        "properties": {
            name: {k: v for k, v in prop.items() if k in ("type", "enum")}
            for name, prop in schema["properties"].items()
        },
    }


def _derivable() -> list[str]:
    return sorted(
        name
        for name, entry in COMMAND_TABLE.items()
        if entry.handler is not None
        and name in CAPABILITIES
        and CAPABILITIES[name].arguments is not None
    )


class TestTheDerivationIsTotal:
    @pytest.mark.parametrize("verb", _derivable())
    def test_every_capability_backed_verb_matches_its_declaration(self, verb):
        """A verb that quietly kept a literal is a verb free to drift from the flow.

        Structure only: property names, wire types, requiredness. The prose is the
        verb's own and is deliberately longer than a form label.
        """
        assert _structure(COMMAND_TABLE[verb].params_schema) == _structure(params_schema_for(verb))

    def test_every_live_verb_but_four_is_capability_backed(self):
        """The count is the point of the exercise, so it is asserted rather than implied.

        Four live verbs are not: `prompt` (`submit` under defaulted provenance),
        and the three that describe the PROTOCOL rather than the session —
        `get_capabilities`, `next_step`, `enumerate_domain`.

        Thirty-six: thirty when 0.9.8 put the eleven off-wire capabilities on
        the wire, plus the extension-config pair, the tree-read pair (`get_tree`,
        `get_entry`) and the extension-request pair (`get_pending_request`,
        `answer_request`). The number is asserted rather than derived so that a verb added
        without a capability, or a capability added without a verb, has to be
        stated here — which is the same thing `test_the_wire_flag_matches_the_
        command_table` asks from the other side.
        """
        live = {name for name, entry in COMMAND_TABLE.items() if entry.handler is not None}
        assert sorted(live - set(CAPABILITIES)) == [
            "enumerate_domain",
            "get_capabilities",
            "next_step",
            "prompt",
        ]
        assert len(live & set(CAPABILITIES)) == 36

    def test_no_declined_verb_names_a_capability(self):
        """§6 A4 survives: `declined_because` is prose no declaration produces."""
        declined = {name for name, entry in COMMAND_TABLE.items() if entry.handler is None}
        assert declined and not declined & set(CAPABILITIES)


class TestTheDomainTypeTable:
    def test_every_domain_has_a_wire_type(self):
        assert set(_DOMAIN_TYPES) == set(DOMAINS)

    def test_a_fixed_string_domain_carries_its_values_as_an_enum(self):
        schema = params_schema_for("complete_message_id")
        assert schema["properties"]["scope"]["enum"] == list(DOMAINS["message_id_scope"].values)

    def test_the_boolean_domain_is_a_boolean_and_not_an_enum_of_two_strings(self):
        """``boolean``'s ``values`` are what a picker shows, not what the wire takes.

        Emitting them would have turned `set_auto_compaction {enabled: true}` into
        `{enabled: "true"}` — the one place where reading the domain naively breaks
        a shipped verb.
        """
        prop = params_schema_for("set_auto_compaction")["properties"]["enabled"]
        assert prop["type"] == "boolean"
        assert "enum" not in prop


class TestWhatItRefuses:
    def test_an_override_for_an_argument_the_capability_does_not_take(self):
        with pytest.raises(ValueError, match="does not take"):
            params_schema_for("set_model", overrides={"model": {"description": "nope"}})

    def test_a_capability_whose_arguments_are_unstated_cannot_be_derived(self):
        with pytest.raises(ValueError, match="cannot be derived"):
            params_schema_for("submit")

    def test_an_unknown_capability_raises_rather_than_returning_an_empty_schema(self):
        with pytest.raises(KeyError):
            params_schema_for("frobnicate")


class TestTheProseStaysHandWritten:
    def test_an_override_replaces_the_form_label(self):
        """`set_model`'s wire description names the config file; its label does not."""
        assert CAPABILITIES["set_model"].arguments[0].description == "Which configured model."
        wire = COMMAND_TABLE["set_model"].params_schema["properties"]["name"]["description"]
        assert "~/.tau/config.json" in wire

    def test_an_override_may_add_a_keyword_the_registry_has_no_field_for(self):
        schema = COMMAND_TABLE["complete_path"].params_schema
        assert schema["properties"]["cursor"]["minimum"] == 0
