#!/usr/bin/env python3
"""Export the agent-facing reference into the FFWF Robotics documentation site.

Reference: docs/AGENT-DOCS.md

``scripts/build_agent_docs.py`` writes ``docs/library/reference/`` for a reader
who has the repository. This script writes the same pages into an MkDocs site
that a reader on the web has instead, under ``docs/tau/reference/api/``.

The body of each exported page is byte-identical to its ``docs/library/
reference/`` counterpart: this script renders through the same
``tau_agent_core.docs_build`` functions and then changes only the title line,
the banner, and the frontmatter. So the two references cannot disagree about
what an object does -- there is one renderer, not two.

The site path is an argument with no default. This repository does not know
where anyone else keeps a checkout, and a guessed path that happens to exist is
how a script writes into the wrong tree.

    venv/bin/python scripts/export_site_reference.py --site ../ffwfrobotics.github.io
    venv/bin/python scripts/export_site_reference.py --site ../ffwfrobotics.github.io --check

``--check`` writes nothing and exits 1 naming the first page that differs, so a
stale export is a failure rather than a discovery.

The nav is maintained too. ``mkdocs.yml`` carries two marker comment lines and
this script replaces the lines between them; a site whose ``mkdocs.yml`` has no
markers is an error naming the lines to add, never a silent set of pages that
appear in no menu.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

from tau_agent_core.docs_build import (
    GENERATED_BANNER,
    PACKAGES,
    CoverageReport,
    DocsBuildError,
    TopicPage,
    collect,
    coverage,
    pages,
    render_topic,
    source_paths,
)

REPO_ROOT = Path(__file__).resolve().parent.parent

SITE_SUBDIR = Path("docs") / "tau" / "reference" / "api"

SITE_BANNER = (
    "<!-- generated by scripts/export_site_reference.py in the tau repository "
    "— do not edit by hand -->"
)

NAV_BEGIN = "# >>> generated by scripts/export_site_reference.py (tau repo)"
NAV_END = "# <<< generated"

VERSION_FILE = Path("tau-coding-agent") / "src" / "tau_coding_agent" / "__init__.py"


class ExportError(Exception):
    """The site or the rendered pages are not the shape this script requires."""


def read_version(repo_root: Path) -> str:
    """The ``__version__`` string of the top package, read without importing it.

    Args:
        repo_root: The tau repository root.

    Returns:
        The version literal, e.g. ``"0.9.7"``.

    Raises:
        ExportError: If the assignment is missing or is not a string literal.
    """
    path = repo_root / VERSION_FILE
    tree = ast.parse(path.read_text(), filename=str(path))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "__version__":
                if not isinstance(node.value, ast.Constant) or not isinstance(
                    node.value.value, str
                ):
                    raise ExportError(f"{path}: __version__ is not a string literal")
                return node.value.value
    raise ExportError(f"{path}: no __version__ assignment")


def site_page(page: TopicPage, body: str) -> str:
    """Re-head one rendered topic page for the site.

    Everything below the banner is passed through untouched, which is the whole
    point: the site and ``docs/library/reference/`` carry the same text.

    Args:
        page: The topic, for its title.
        body: The output of :func:`render_topic` for that topic.

    Returns:
        The markdown file, with site frontmatter and the site banner.

    Raises:
        ExportError: If ``body`` is not the four-line head this transformation
            expects, which means ``render_topic`` changed shape.
    """
    lines = body.split("\n")
    if len(lines) < 4 or not lines[0].startswith("# ") or lines[2] != GENERATED_BANNER:
        raise ExportError(
            f"{page.topic}: render_topic no longer produces "
            "'# title' / '' / banner / '' as its first four lines; "
            "scripts/export_site_reference.py re-heads that shape and must be updated"
        )
    head = [
        "---",
        f'title: "{page.title}"',
        "---",
        "",
        f"# {page.title}",
        "",
        SITE_BANNER,
    ]
    return "\n".join(head + lines[3:])


def site_index(built: list[TopicPage], report: CoverageReport, version: str) -> str:
    """Render the API section's own index page.

    Args:
        built: The topic pages, in nav order.
        report: Coverage over the same objects, published rather than hidden.
        version: The tau version these pages were generated from.

    Returns:
        The markdown file.
    """
    complete = report.complete
    total = report.total
    percent = f"{report.fraction * 100:.1f}%"

    lines = [
        "---",
        'title: "API"',
        "---",
        "",
        "# API",
        "",
        SITE_BANNER,
        "",
        "Every object marked `@agent_facing` in the τ source, grouped by topic.",
        "This is the surface an extension author or an agent calls; it is",
        "generated from the docstrings, so a page here is as current as the code",
        "it was built from.",
        "",
        '!!! note "Generated"',
        f"    Built from τ {version} by `scripts/export_site_reference.py` in the",
        "    τ repository. Of the "
        f"{total} marked objects, {complete} ({percent}) document every parameter",
        "    and every return value. The rest appear here with whatever they",
        "    carry — omitting them would make this page quietly incomplete",
        "    instead of visibly so.",
        "",
        "The prose pages one level up say how the packages fit together;",
        "these say what each name is.",
        "",
        "| Page | Defines |",
        "|---|---|",
    ]
    for page in built:
        counts: dict[str, int] = {}
        for obj in page.objects:
            counts[obj.name] = counts.get(obj.name, 0) + 1
        names = ", ".join(
            f"`{obj.path if counts[obj.name] > 1 else obj.name}`" for obj in page.objects
        )
        lines.append(f"| [{page.title}]({page.topic}.md) | {names} |")
    lines.append("")
    return "\n".join(lines)


def nav_block(built: list[TopicPage], indent: str) -> list[str]:
    """The mkdocs nav lines for the API section, at the marker's indentation.

    Page titles come from each page's own frontmatter, so no label is spelled
    here — a renamed topic renames its nav entry with no second edit.

    Args:
        built: The topic pages, in nav order.
        indent: The leading whitespace of the ``NAV_BEGIN`` marker line.

    Returns:
        One line per nav entry, including the ``API:`` opener.
    """
    inner = indent + "    "
    lines = [f"{indent}- API:", f"{inner}- tau/reference/api/index.md"]
    lines += [f"{inner}- tau/reference/api/{page.topic}.md" for page in built]
    return lines


def render_all(repo_root: Path) -> tuple[dict[str, str], list[str]]:
    """Render every site page and the nav lines they need.

    Args:
        repo_root: The tau repository root.

    Returns:
        ``(files, nav)`` -- filename to contents under the API directory, and
        the nav lines with a placeholder indentation the caller re-indents.

    Raises:
        DocsBuildError: On a fault in the marked surface.
        ExportError: On a rendered page this script cannot re-head.
    """
    objects, warnings = collect(PACKAGES, source_paths(repo_root))
    built = pages(objects)
    report = coverage(objects, warnings)
    version = read_version(repo_root)

    files = {f"{page.topic}.md": site_page(page, render_topic(page)) for page in built}
    files["index.md"] = site_index(built, report, version)
    return files, nav_block(built, "")


def _nav_indent(line: str) -> str:
    """The leading whitespace of a marker line."""
    return line[: len(line) - len(line.lstrip())]


def splice_nav(config_text: str, nav: list[str]) -> str:
    """Replace the marked nav region of ``mkdocs.yml``.

    Only the lines between the two markers change; every comment, key and blank
    line elsewhere in the file survives byte for byte, which is why this is line
    surgery rather than a YAML round-trip.

    Args:
        config_text: The current ``mkdocs.yml``.
        nav: The nav lines from :func:`nav_block`, indented from column zero.

    Returns:
        The new ``mkdocs.yml`` text.

    Raises:
        ExportError: If either marker is missing, duplicated, or out of order.
    """
    lines = config_text.split("\n")
    starts = [i for i, line in enumerate(lines) if line.strip() == NAV_BEGIN]
    ends = [i for i, line in enumerate(lines) if line.strip() == NAV_END]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        raise ExportError(
            "mkdocs.yml must contain exactly one marker pair, in order. Add them "
            "inside the Tau 'Reference:' nav node:\n"
            f"    {NAV_BEGIN}\n"
            f"    {NAV_END}"
        )
    indent = _nav_indent(lines[starts[0]])
    body = [indent + line if line else line for line in nav]
    return "\n".join(lines[: starts[0] + 1] + body + lines[ends[0] :])


def resolve_site(site: Path) -> tuple[Path, Path]:
    """Locate the API directory and ``mkdocs.yml`` in a site checkout.

    Args:
        site: The path passed to ``--site``.

    Returns:
        ``(api_dir, mkdocs_yml)``. The directory need not exist yet.

    Raises:
        ExportError: If ``site`` is not a checkout of the documentation site.
            A path that is merely wrong is caught here rather than by writing
            markdown into it.
    """
    config = site / "mkdocs.yml"
    anchor = site / "docs" / "tau" / "reference" / "index.md"
    if not config.is_file() or not anchor.is_file():
        raise ExportError(f"{site} is not the documentation site: expected {config} and {anchor}")
    return site / SITE_SUBDIR, config


def _stale(api_dir: Path, written: set[str]) -> list[Path]:
    """Generated pages in ``api_dir`` that this export no longer produces.

    A file without the banner is not ours and is never returned, so a hand-added
    page under the generated directory stops the export instead of vanishing.

    Args:
        api_dir: The API directory.
        written: Filenames this export produces.

    Returns:
        The files to remove.

    Raises:
        ExportError: On a file in ``api_dir`` that this script did not write.
    """
    stale = []
    for path in sorted(api_dir.glob("*.md")):
        if path.name in written:
            continue
        if SITE_BANNER not in path.read_text():
            raise ExportError(
                f"{path} is under the generated directory but was not generated "
                "by this script. Move it before exporting; refusing to delete it."
            )
        stale.append(path)
    return stale


def check(api_dir: Path, config: Path, files: dict[str, str], nav: list[str]) -> list[str]:
    """Compare a site checkout against a fresh render.

    Args:
        api_dir: The API directory.
        config: The site's ``mkdocs.yml``.
        files: Filename to contents, from :func:`render_all`.
        nav: The nav lines, indented from column zero.

    Returns:
        One line per difference, empty when the site is current.
    """
    faults = []
    for name, text in sorted(files.items()):
        path = api_dir / name
        if not path.is_file():
            faults.append(f"missing: {path}")
        elif path.read_text() != text:
            faults.append(f"stale: {path}")
    if api_dir.is_dir():
        for path in _stale(api_dir, set(files)):
            faults.append(f"orphan: {path}")
    current = config.read_text()
    if splice_nav(current, nav) != current:
        faults.append(f"stale nav: {config}")
    return faults


def write(api_dir: Path, config: Path, files: dict[str, str], nav: list[str]) -> None:
    """Write the pages and the nav into a site checkout.

    Args:
        api_dir: The API directory, created if absent.
        config: The site's ``mkdocs.yml``.
        files: Filename to contents, from :func:`render_all`.
        nav: The nav lines, indented from column zero.
    """
    api_dir.mkdir(parents=True, exist_ok=True)
    for path in _stale(api_dir, set(files)):
        path.unlink()
        print(f"removed {path}")
    for name, text in sorted(files.items()):
        path = api_dir / name
        if path.is_file() and path.read_text() == text:
            continue
        path.write_text(text)
        print(f"wrote {path}")
    current = config.read_text()
    updated = splice_nav(current, nav)
    if updated != current:
        config.write_text(updated)
        print(f"wrote {config}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--site",
        required=True,
        type=Path,
        help="Path to the ffwfrobotics.github.io checkout. No default: this "
        "repository does not know where yours is.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Write nothing; exit 1 if the site differs from a fresh render.",
    )
    args = parser.parse_args(argv)

    try:
        api_dir, config = resolve_site(args.site)
        files, nav = render_all(REPO_ROOT)
        if args.check:
            faults = check(api_dir, config, files, nav)
            for fault in faults:
                print(fault, file=sys.stderr)
            if faults:
                print(
                    f"{len(faults)} difference(s). Re-run without --check to update.",
                    file=sys.stderr,
                )
                return 1
            print(f"{len(files)} page(s) current")
            return 0
        write(api_dir, config, files, nav)
    except (DocsBuildError, ExportError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
